# Generated by Django 2.2 on 2022-03-30 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220330_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Физическое лицо', 'verbose_name_plural': 'Физические лица'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 3, 30, 18, 51, 16, 717863), null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='patronymic',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Женский'), (1, 'Мужской')], default=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
