# Generated by Django 2.2 on 2022-03-30 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220330_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата рождения'),
        ),
    ]
