# Generated by Django 2.2 on 2022-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220330_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='Имя')),
                ('content_type', models.CharField(max_length=40, null=True, verbose_name='Тип')),
                ('codename', models.CharField(max_length=40, null=True, verbose_name='Кодовое название')),
            ],
        ),
    ]
