# Generated by Django 2.2 on 2022-04-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220401_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
