# Generated by Django 2.2 on 2022-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='Имя')),
                ('content_type', models.CharField(max_length=40, null=True, verbose_name='Тип')),
                ('codename', models.CharField(max_length=40, null=True, verbose_name='Кодовое название')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Group',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='Имя')),
                ('content_type', models.CharField(max_length=40, null=True, verbose_name='Тип')),
                ('codename', models.CharField(max_length=40, null=True, verbose_name='Кодовое название')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
    ]
