# Generated by Django 2.2 on 2022-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_group_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='Имя')),
                ('content_type', models.CharField(choices=[('LE', 'Log entry'), ('GR', 'Group'), ('PR', 'Permission'), ('US', 'User')], default='LE', max_length=40, verbose_name='Тип')),
                ('codename', models.CharField(max_length=2, null=True, verbose_name='Кодовое название')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permission',
            },
        ),
    ]
