# Generated by Django 2.2 on 2022-04-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
    ]
