# Generated by Django 2.2 on 2022-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220401_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=40, null=True, verbose_name='Кодовое название'),
        ),
    ]
