# Generated by Django 2.2 on 2022-04-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220404_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentType',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
